plugins:
  - serverless-python-requirements
  - serverless-log-forwarding

custom:
  pythonRequirements:
    dockerizePip: false
  logForwarding:
    destinationARN: {"Fn::ImportValue": "${env:SUMOLOGIC_LAMBDA_ARN_EXPORT_NAME}"}

service: MV-opsgenie-centreon

provider:
  name: aws
  runtime: python3.6
  stage: ${env:ENV}
  memory: 128
  region: ${env:AWS_REGION}
  variableSyntax: "\\${(?!AWS::)(env:[ :a-zA-Z0-9._,\\-\\/\\(\\)]+?)}"
  stackTags:
    FRAMEWORK: serverless
  vpc:
    securityGroupIds:
      - "${env:AWS_SG}"
    subnetIds:
      - "${env:AWS_SUBNET_A}"

package:
  exclude:
    - .gitignore
    - .git/**
    - docker-compose.yml
    - serverless.yml
    - requirements.txt
    - node_modules/**
    - package.json
    - yarn.lock
    - Makefile
    - README.md

functions:
  acknowledge:
    handler: lambda.handler
    events:
      - sns: MV-opsgenie-centreon-acknowledge-${env:ENV}
    environment:
      CENTREON_URL: ${env:CENTREON_URL}
      CENTREON_USERALIAS: ${env:CENTREON_USERALIAS}
      CENTREON_PASSWORD: ${env:CENTREON_PASSWORD}
  test_connectivity:
    handler: lambda.test_connectivity
    environment:
      CENTREON_URL: ${env:CENTREON_URL}
      CENTREON_USERALIAS: ${env:CENTREON_USERALIAS}
      CENTREON_PASSWORD: ${env:CENTREON_PASSWORD}

resources:
  Resources:
    SNSTopicPolicy:
      Type: AWS::SNS::TopicPolicy
      Properties:
        PolicyDocument:
          Id: __default_policy_ID
          Statement:
          - Action:
            - SNS:Publish
            - SNS:RemovePermission
            - SNS:SetTopicAttributes
            - SNS:DeleteTopic
            - SNS:ListSubscriptionsByTopic
            - SNS:GetTopicAttributes
            - SNS:Receive
            - SNS:AddPermission
            - SNS:Subscribe
            Condition:
              StringEquals:
                AWS:SourceOwner: '${AWS::AccountId}'
            Effect: Allow
            Principal:
              AWS: '*'
            Resource:
              Ref: SNSTopicMVopsgeniecentreonacknowledge${env:ENV}
            Sid: __default_statement_ID
          - Action: SNS:Publish
            Effect: Allow
            Principal:
              AWS: arn:aws:iam::808708019265:root # OpsGenie account
            Resource:
              Ref: SNSTopicMVopsgeniecentreonacknowledge${env:ENV}
            Sid: __console_pub_0
          Version: '2008-10-17'
        Topics:
          - Ref: SNSTopicMVopsgeniecentreonacknowledge${env:ENV}
